stages:
  - deploy

pages:
  stage: deploy
  image: node:latest
  script:
    - mkdir public
    - cd public
    - wget https://artmosphere.gitlab.io/electron/artmosphere.AppImage
    - wget https://artmosphere.gitlab.io/electron/artmosphere_setup_0.0.15.exe
    - wget https://artmosphere.gitlab.io/electron/artmosphere_setup_0.0.15.exe.blockmap
    - wget https://artmosphere.gitlab.io/electron/latest-linux.yml
    - wget https://artmosphere.gitlab.io/electron/latest.yml
    - sed -i "s/version/$(node version.js)/" ./dist/index.html
    - cp dist/index.html public/
  artifacts:
    paths:
      - public
  only:
    - master
