build:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  image: electronuserland/builder:wine
  stage: build
  script:
    - node -v
    - cd angular
    - if [ -z ${PULL_LATEST_ANGULAR_SUBMODULE+x} ]; then echo 'Already pulled fixed version of angular submodule.'; else git pull origin master; fi
    - npm install
    - npx ng build --prod --output-path ../html --base-href ./index.html
    - cd ..
    - npm i --save-dev node@10.1.0
    - npx node -v
    - npm install
    - npm i --save-dev @types/node@8.10.30
    - npm run build
    - npx electron-builder -l --x64
    - ls -la dist/
    - rm -rf dist/*unpacked
  artifacts:
    paths:
       - dist/
  only:
    - master

pages:
  image: alpine:latest
  stage: deploy
  script:
    - mv dist public
  dependencies:
    - build
  artifacts:
    paths:
      - public
  only:
    - master