stages:
  - prepare
  - build
  - deploy

html:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  image: node:latest
  stage: prepare
  tags:
    - docker
  script:
    - node -v
    - cd angular
    - if [ -z ${PULL_LATEST_ANGULAR_SUBMODULE+x} ]; then echo 'Already pulled fixed version of angular submodule.'; else git pull origin master; fi
    - npm install
    - npx ng build --prod --output-path ../html
  artifacts:
    paths:
       - html/
  only:
    - master

build:
  image: electronuserland/builder:wine
  stage: build
  dependencies:
    - html
  tags:
    - docker
  script:
    - node -v
    - npm install
    - npm run build
    - ls -la dist/
    - rm -rf dist/*unpacked
    - mv dist dist-linux
  artifacts:
    paths:
       - dist-linux/
  only:
    - master
buildforwindows:
  image: electronuserland/builder:wine
  cache:
    key: "$CI_JOB_ID"
    paths:
      - node_modules/
  stage: build
  dependencies:
    - html
  tags:
    - windows
  script:
    - PATH=$PATH:/cygdrive/c/Program\ Files/nodejs/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin
    - PATH=$PATH:/cygdrive/c/Users/$(whoami)/AppData/Roaming/npm
    - PATH=$PATH:/cygdrive/c/Users/$(whoami)/AppData/Roaming/npm/node_modules/.bin
    - PATH=$PATH:/cygdrive/c/Users/$(whoami)/AppData/Roaming/npm/node_modules/windows-build-tools/node_modules/.bin
    - PATH=$PATH:/cygdrive/c/Users/$(whoami)/.windows-build-tools/python27
    - node -v
    - npm install
    - npm run buildforwindows
    - ls -la dist/
    - rm -rf dist/*unpacked
  artifacts:
    paths:
       - dist/
  only:
    - master

pages:
  stage: deploy
  script:
    - mv dist-linux/* dist/
    - mv dist public
  dependencies:
    - build
    - buildforwindows
  artifacts:
    paths:
      - public
  only:
    - master
