image:
  - Visual Studio 2017
  - Ubuntu

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - git submodule -q update --init --recursive
  - npm install
  - cd angular
  - npm install
  - cd ..

build_script:
  - cd angular
  - npx ng build --prod --output-path ../html
  - cd ..
  - cmd: npm run buildforwindows
  - sh: npm run build

test: off