image:
  - Visual Studio 2017
  - Ubuntu1804

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

environment:
  nodejs_version: 10.15.0
install:
  - cmd: powershell Install-Product node $env:nodejs_version x64
  - sh: nvm install $nodejs_version
  - git submodule -q update --init --recursive
  - npm install
  - cd angular
  - npm install
  - cd ..

build_script:
  - cd angular
  - npx ng build --prod --output-path ../html
  - cd ..
  - cmd: npm run buildforwindows
  - sh: npm run build

test: off
